#%RAML 1.0 ObjectTypeDeclaration
type: object
properties:
    content-id:
        type: string
        required: true
    content-encryption-key:
        type: string
        required: true
    protected-content-location:
        type: string
        required: true
    protected-content-length:
        type: string
        required: true
    protected-content-sha256:
        type: string
        required: true
    protected-content-disposition:
        type: string
        required: true
