name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - name: install raml2html
        run: npm i -g raml2html
      - name: build
        run: |
          mkdir build
          raml2html -i lcp.raml -o build/lcp.html
          raml2html -i lsd.raml -o build/lsd.html
      - name: commit
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
